name: India Trend Radar Scheduler

on:
  schedule:
    # Runs every day at 6:00 AM IST (00:30 UTC)
    - cron: '30 0 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  data-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Google Trends

      - name: Run Google Trends
        run: python -m scripts.google_trends

      # News Collection
      # Uncomment when news_fetch.py is ready

      # - name: Run News Collection
      #   run: python -m scripts.news_fetch

      # YouTube Collection
      
      #- name: Run YouTube Collection
       # run: python -m scripts.youtube_fetch

      - name: Commit Updated Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .

          git diff --cached --quiet || git commit -m "Daily automated data collection"

          git push
